---
title: "Adversarial"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, message = FALSE)
library(dplyr)
library(ggplot2)
library(compare)
library(rjson)
library(data.table)

#setwd("C:/Users/bcalvo/Box/bcalvo/Claim-Verification-FakeNews/")
# REMEMBER: the working directory of the R sessions and the working directory of the notebook are different things!!!!
```

```{r pressure, echo=FALSE}
adver<- read.csv("~/Desktop/ClaimVer/Claim-Verification-FakeNews/code/outputs/F-base-bert-2/adver-results.tsv", header = FALSE, sep='\t')

adver_results <- adver %>%
  #filter(V4!=2)%>%
  rowwise() %>%
  mutate(output= which.max(list(V1,V2,V3))-1)%>%
  #filter(output!=2)%>%
  mutate(right = sum(V4==output, na.rm=T))

print(sum(adver_results$right)/nrow(adver_results))

```
```{r pressure, echo=FALSE}
sem_adver<- read.csv("~/Desktop/ClaimVer/Claim-Verification-FakeNews/code/outputs/f_sembert-concat_True-agg_False-20batch_size-250seq_length-12n_aspect-tags1/adver-results.tsv", header = FALSE, sep='\t')

sem_adver_results <- sem_adver %>%
  #filter(V4!=2)%>%
  rowwise() %>%
  mutate(output= which.max(list(V1,V2,V3))-1)%>%
  #filter(output!=2)%>%
  mutate(right = sum(V4==output, na.rm=T))

print(sum(sem_adver_results$right)/nrow(sem_adver_results))

```


```{r explore}
ad<- read.table("~/Desktop/ClaimVer/Claim-Verification-FakeNews/data/X_tests/adversarial_examples.tsv", sep="\t", header=FALSE, comment.char="#", na.strings=".", stringsAsFactors=FALSE, quote="", fill=TRUE)

```



