---
title: "saliency"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = 'C:/Users/bcalvo/Box/bcalvo/Claim-Verification-FakeNews/')
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
library(dplyr)
library(ggplot2)
library(compare)
library(rjson)
library(data.table)
library(jsonlite)
library(tidyverse)
library(forcats)

#setwd("C:/Users/bcalvo/Box/bcalvo/Claim-Verification-FakeNews/")
# REMEMBER: the working directory of the R sessions and the working directory of the notebook are different things!!!!

```


```{r select_data}

get_format_sal <- function(list_metrics,id, list_metric_names, true_label, props=FALSE){
  final_list <- data.frame(V1=integer(), ID=factor(), stat=character(), order=factor()) 
  for(i in 1:length(list_metrics)) {
    #print(i)
    example <- list_metrics[[i]][id,]

    token_names <- example%>%
      select(starts_with("tokens.token"))%>%
      t()%>%
      as.data.frame()
    
    which_tokens = paste("tokens", true_label, sep=".")
    which_props = paste("props", true_label, sep=".")

    token_values <- example%>%
      select(starts_with(which_tokens))%>%
      t()%>%
      as.data.frame()


  token_values['ID'] <- token_names[,1]
  token_values$ID = as.factor(token_values$ID)
  token_values$V1 = as.numeric(token_values$V1)
  token_values <- token_values%>%
    mutate(mean=mean(token_values$V1))%>%
    mutate(normalised=V1-mean)
  
  #print(token_values$V1)
  #print(token_values$normalised)
  
  #print('before filtering')
  #print(nrow(token_values))
  
  #print(token_values$ID)

  token_values <- token_values%>%
    filter(ID != '[PAD]')
  
  #print(nrow(token_values))
  
  if (props==TRUE){
    tag_names <- example%>%
      select(starts_with("props.prop"))%>%
      t()%>%
      as.data.frame()


    tag_values <- example%>%
      select(starts_with(which_props))%>%
      t()%>%
      as.data.frame()
    
    tag_values['ID'] <- tag_names[,1]
    tag_values$ID = as.factor(tag_values$ID)
    tag_values$V1 = as.numeric(tag_values$V1)
    tag_values <- tag_values%>%
      mutate(mean=mean(tag_values$V1))%>%
      mutate(normalised=V1-mean)
    
    #print(colnames(tag_values))
    
    token_values <- rbind(token_values, tag_values)
    
  }
  
  token_values["stat"] <- as.factor(replicate(nrow(token_values), list_metric_names[i]))
  token_values['order'] <- c(1:nrow(token_values))
  token_values['order'] <- as.factor(token_values$order)

  final_list <- rbind(final_list, token_values)
  }
  


  return(final_list)
  
}
```


### Sembert tags1

```{r load_data_s}
lines <- readLines("C:/Users/bcalvo/Box/bcalvo/Claim-Verification-FakeNews/experiment-5/outputs/sembert_tags1/saliency_scores/saliency_scores/scores_sal_l2")
lines <- lapply(lines, fromJSON)
lines <- lapply(lines, unlist)
metric11 <- bind_rows(lines)
metric11 <- metric11[order(metric11$tokens.token2),]

lines <- readLines("C:/Users/bcalvo/Box/bcalvo/Claim-Verification-FakeNews/experiment-5/outputs/sembert_tags1/saliency_scores/saliency_scores/scores_guided_l2")
lines <- lapply(lines, fromJSON)
lines <- lapply(lines, unlist)
metric12 <- bind_rows(lines)
metric12 <- metric12[order(metric12$tokens.token2),]

lines <- readLines("C:/Users/bcalvo/Box/bcalvo/Claim-Verification-FakeNews/experiment-5/outputs/sembert_tags1/saliency_scores/saliency_scores/scores_inputx_l2")
lines <- lapply(lines, fromJSON)
lines <- lapply(lines, unlist)
metric13 <- bind_rows(lines)
metric13 <- metric13[order(metric13$tokens.token2),]


lines <- readLines("C:/Users/bcalvo/Box/bcalvo/Claim-Verification-FakeNews/experiment-5/outputs/sembert_tags1/saliency_scores/saliency_scores/scores_sal_l2_3")
lines <- lapply(lines, fromJSON)
lines <- lapply(lines, unlist)
metric14 <- bind_rows(lines)
metric14 <- metric14[order(metric14$tokens.token2),]

lines <- readLines("C:/Users/bcalvo/Box/bcalvo/Claim-Verification-FakeNews/experiment-5/outputs/sembert_tags1/saliency_scores/saliency_scores/scores_guided_l2_3")
lines <- lapply(lines, fromJSON)
lines <- lapply(lines, unlist)
metric15 <- bind_rows(lines)
metric15 <- metric15[order(metric15$tokens.token2),]

lines <- readLines("C:/Users/bcalvo/Box/bcalvo/Claim-Verification-FakeNews/experiment-5/outputs/sembert_tags1/saliency_scores/saliency_scores/scores_inputx_l2_3")
lines <- lapply(lines, fromJSON)
lines <- lapply(lines, unlist)
metric16 <- bind_rows(lines)
metric16 <- metric16[order(metric16$tokens.token2),]
```

```{r}
list_metrics = list(metric11, metric12, metric13, metric14, metric15, metric16)
list_metric_names = c('saliency_l2','guided_l2','inputx_l2','saliency_l2_2','guided_l2_2','inputx_l2_2')
list_labels = list('0', '1', '1', '2', '0', '1', '0')

for (i in 1:range(length(list_labels))){
  print('example number')
  print(i)
metrics_list<- get_format_sal(list_metrics, i, list_metric_names,list_labels[i], props = FALSE)

#token_values <- get_format_sal(example1_1)

metrics_list%>%
  #mutate(ID = fct_reorder(ID,order)) %>%
  #filter(ID!='NA')%>%
  ggplot(aes(x=order, y=stat, fill=normalised)) + geom_tile()+
  scale_fill_gradient(low = "white", high = "#4186BE") +
  theme(axis.text.x = element_text(angle = 70, size = 7))+
  scale_x_discrete(labels=metrics_list[["ID"]][1:299])+
  #xlim(0, length(unique(metrics_list$ID)))
  labs(x="Token",y="Metric")

name_file = paste0("visuals/saliency/sembert_example", as.character(i))
name_file =paste0(name_file, '.png')
print(name_file)

ggsave(file=name_file, width=30, height=4, dpi=400)

}
```

### BERT tags1

```{r load_data_s}
lines <- readLines("C:/Users/bcalvo/Box/bcalvo/Claim-Verification-FakeNews/experiment-5/outputs/bert_base/saliency_scores/right_scores/scores_sal_l2_3")
lines <- lapply(lines, fromJSON)
lines <- lapply(lines, unlist)
metric21 <- bind_rows(lines)
metric21 <- metric21[order(metric21$tokens.token2),]

lines <- readLines("C:/Users/bcalvo/Box/bcalvo/Claim-Verification-FakeNews/experiment-5/outputs/bert_base/saliency_scores/right_scores/scores_guided_l2_3")
lines <- lapply(lines, fromJSON)
lines <- lapply(lines, unlist)
metric22 <- bind_rows(lines)
metric22 <- metric22[order(metric22$tokens.token2),]

lines <- readLines("C:/Users/bcalvo/Box/bcalvo/Claim-Verification-FakeNews/experiment-5/outputs/bert_base/saliency_scores/right_scores/scores_inputx_l2_3")
lines <- lapply(lines, fromJSON)
lines <- lapply(lines, unlist)
metric23 <- bind_rows(lines)
metric23 <- metric23[order(metric23$tokens.token2),]

lines <- readLines("C:/Users/bcalvo/Box/bcalvo/Claim-Verification-FakeNews/experiment-5/outputs/bert_base/saliency_scores/right_scores/scores_sal_l2_1")
lines <- lapply(lines, fromJSON)
lines <- lapply(lines, unlist)
metric24 <- bind_rows(lines)
metric24 <- metric24[order(metric24$tokens.token2),]

lines <- readLines("C:/Users/bcalvo/Box/bcalvo/Claim-Verification-FakeNews/experiment-5/outputs/bert_base/saliency_scores/right_scores/scores_guided_l2_1")
lines <- lapply(lines, fromJSON)
lines <- lapply(lines, unlist)
metric25 <- bind_rows(lines)
metric25 <- metric25[order(metric25$tokens.token2),]

lines <- readLines("C:/Users/bcalvo/Box/bcalvo/Claim-Verification-FakeNews/experiment-5/outputs/bert_base/saliency_scores/right_scores/scores_inputx_l2_1")
lines <- lapply(lines, fromJSON)
lines <- lapply(lines, unlist)
metric26 <- bind_rows(lines)
metric26 <- metric26[order(metric26$tokens.token2),]

```

```{r}
list_metrics = list(metric21, metric22, metric23)
list_metric_names = c('saliency_l2','guided_l2','inputx_l2')
list_labels = list('0', '1', '1', '2', '0', '1', '0')

for (i in 1:range(length(list_labels))){
  print(i)
metrics_list<- get_format_sal(list_metrics, i, list_metric_names,list_labels[i], props = FALSE)

#token_values <- get_format_sal(example1_1)

metrics_list%>%
  #mutate(ID = fct_reorder(ID,order)) %>%
  #filter(ID!='NA')%>%
  ggplot(aes(x=order, y=stat, fill=normalised)) + geom_tile()+
  scale_fill_gradient(low = "white", high = "#4186BE") +
  theme(axis.text.x = element_text(angle = 70, size = 7))+
  scale_x_discrete(labels=metrics_list[["ID"]][1:299])+
  #xlim(0, length(unique(metrics_list$ID)))
  labs(x="Token",y="Metric")

name_file = paste0("visuals/saliency/bert_example", as.character(i))
name_file =paste0(name_file, '.png')
print(name_file)

ggsave(file=name_file, width=30, height=4, dpi=400)

}
```

## Comparison

```{r}
#list_metrics = list(metric21, metric14)
#list_metric_names = c('saliency_bert','saliency_sembert')
list_metrics = list(metric13, metric16, metric12, metric15, metric11, metric14, metric23, metric26, metric22, metric25, metric21, metric24)
list_metric_names = c('sembert_inputx_1','sembert_inputx_2','sembert_guided_1','sembert_guided_2','sembert_saliency_1','sembert_saliency_2', 'bert_inputx_1','bert_inputx_2','bert_guided_1','bert_guided_2', 'bert_saliency_1', 'bert_saliency_2')
#list_labels = list('1', '0', '2', '1', '1', '0', '0')

for (i in 1:range(length(list_labels))){
  print(i)
metrics_list<- get_format_sal(list_metrics, i, list_metric_names,list_labels[i], props = FALSE)

#token_values <- get_format_sal(example1_1)

metrics_list%>%
  #mutate(ID = fct_reorder(ID,order)) %>%
  #filter(ID!='NA')%>%
  ggplot(aes(x=order, y=stat, fill=normalised)) + geom_tile()+
  scale_fill_gradient(low = "white", high = "#4186BE") +
  theme(axis.text.x = element_text(angle = 70, size = 7))+
  scale_x_discrete(labels=metrics_list[["ID"]][1:299])+
  #xlim(0, length(unique(metrics_list$ID)))
  labs(x="Token",y="Metric")

name_file = paste0("visuals/saliency/comparison", as.character(i))
name_file =paste0(name_file, '.png')
print(name_file)

ggsave(file=name_file, width=30, height=4, dpi=400)

}
```

## Plots for report

```{r telemundo}
i = 6

metrics_list<- get_format_sal(list_metrics, i, list_metric_names,list_labels[i], props = FALSE)

#token_values <- get_format_sal(example1_1)

metrics_list%>%
  #mutate(ID = fct_reorder(ID,order)) %>%
  filter(as.integer(order)< 100)%>%
  ggplot(aes(x=order, y=stat, fill=normalised)) + geom_tile()+
  scale_fill_gradient(low = "white", high = "#4186BE") +
  theme(axis.text.x = element_text(angle = 70, size = 12), axis.text.y = element_text(size = 12))+
  scale_x_discrete(labels=metrics_list[["ID"]][1:299])+
  #theme(axis.text.x = element_blank(), axis.text.y=element_blank())+
  #xlim(0, length(unique(metrics_list$ID)))
  labs(x="Token",y="Metric")

name_file = paste0("visuals/saliency/telemundo_example", as.character(i))
name_file =paste0(name_file, '.png')
print(name_file)

ggsave(file=name_file, width=30, height=4, dpi=400) #width=9, height=2, dpi=100
```



## Sembert Gold


```{r load_data_s}

lines <- readLines("C:/Users/bcalvo/Box/bcalvo/Claim-Verification-FakeNews/experiment-5/outputs/gold_sembert_tags1/saliency/scores_sal_l2_1")
lines <- lapply(lines, fromJSON)
lines <- lapply(lines, unlist)
metric11 <- bind_rows(lines)
lines <- readLines("C:/Users/bcalvo/Box/bcalvo/Claim-Verification-FakeNews/experiment-5/outputs/gold_sembert_tags1/saliency/scores_guided_l2_1")
lines <- lapply(lines, fromJSON)
lines <- lapply(lines, unlist)
metric21 <- bind_rows(lines)
lines <- readLines("C:/Users/bcalvo/Box/bcalvo/Claim-Verification-FakeNews/experiment-5/outputs/gold_sembert_tags1/saliency/scores_inputx_l2_1")
lines <- lapply(lines, fromJSON)
lines <- lapply(lines, unlist)
metric31 <- bind_rows(lines) # aqui nomes hi ha un valor per token, pero al json n'hi ha 3 :S

list_metrics <- list(metric11,metric21,metric31)
list_metric_names <- c('saliency_l2','guided_l2','inputx_l2')

# 10 is refutes example
# 1 is supports example
```


```{r plot_support_s}
#for (i in 1:range(10)){
#  print(i)
metrics_list<- get_format_sal(list_metrics, 8, list_metric_names, '1', props = TRUE)



metrics_list%>%
  #mutate(ID = fct_reorder(ID,order)) %>%
  #filter(ID!='NA')%>%
  ggplot(aes(x=order, y=stat, fill=V1)) + geom_tile()+
  scale_fill_gradient(low = "white", high = "#4186BE") +
  theme(axis.text.x = element_text(angle = 70, size = 7))+
  scale_x_discrete(labels=metrics_list[["ID"]][1:299])+
  #xlim(0, length(unique(metrics_list$ID)))
  labs(x="Token",y="Metric")

#name_file = paste0("image_gold", as.character(i))
#name_file =paste0(name_file, '.png')

#ggsave(file=name_file, width=30, height=4, dpi=400)

#}
  

ggsave(file="visuals/saliency/gold_example.png", width=30, height=4, dpi=400)

```